spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_db_dev
    username: payments_user
    password: payments_pass
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.payments: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  authorize-net:
    sandbox: true
